PracticaActual/Models/ErrorViewModel.cs
using System;

namespace PracticaActual.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PracticaActual/Models/Pokemon.cs
namespace PracticaActual.Models
{
    public class Pokemon
    {
        public int Id { get; set;}
        public int Nombre { get; set;}
        public int Foto { get; set;}
    }
}

PracticaActual/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PracticaActual.Models;

namespace PracticaActual.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PracticaActual/Controllers/PokemonController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using PracticaActual.Data;
using PracticaActual.Models;

namespace PracticaActual.Controllers
{
   
    public class PokemonController : Controller
    {
        private PokedexContext _context;
        public PokemonController(PokedexContext context)
        {
            _context = context;
        }
        public IActionResult Nuevo(){
            return View();
        }
        [HttpPost]
        public IActionResult Nuevo(Pokemon p){
            if(ModelState.IsValid){
                _context.Add(p);
                _context.SaveChanges();
                
                return RedirectToAction("Lista");
            }
            return View(p);
        }

        public IActionResult Lista(){
            var pokemones = _context.Pokemones.OrderBy(x => x.Nombre).ToList();
            return View(pokemones);
        }
    }

}

PracticaActual/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PracticaActual/Views/Pokemon/Lista.cshtml
@model List<Pokemon>
<h1>lista de cuidades pokemones</h1>
if(Model.Count == 0){
    <div class="alert alert-warning text-center">Aun no hay cuidades</div>
}else{
    <ol>
    @foreach (var p in Model)
    {
        <li class="d-flex">
            <div><img scr="@p.Foto"></div>
            <div>@p.Nombre</div>
        </li>
        
    }
    </ol>
}

PracticaActual/Views/Pokemon/Nuevo.cshtml
@model Pokemon
<h1>Registrar Cuidad</h1>

<form method="post">
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Foto"></label>
        <input asp-for="Foto" class="form-control">
    </div>
    <button class="btn btn-primary">Enviar</button>
</form>

PracticaActual/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaActual</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticaActual</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pokemon" asp-action="Nuevo">Añadir Cuidad Pokemon</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pokemon" asp-action="Lista">Lista de Cuidades Pokemon</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PracticaActual - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>